// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbqpdz2pTQRUr9--EKWpopbAkOBXCHQ4w',
    appId: '1:78639101948:web:429fa5ea572af863606479',
    messagingSenderId: '78639101948',
    projectId: 'fir-flutter-codelab-39c7d',
    authDomain: 'fir-flutter-codelab-39c7d.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-39c7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNxgb6Akhhos62u_18LE-JbRw0Xia7i1A',
    appId: '1:78639101948:android:ccadb5ebd45b71d0606479',
    messagingSenderId: '78639101948',
    projectId: 'fir-flutter-codelab-39c7d',
    storageBucket: 'fir-flutter-codelab-39c7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFtc96wY31YzUZgykJQZcDnt7T-SEpu8Q',
    appId: '1:78639101948:ios:0207e740d93e4a34606479',
    messagingSenderId: '78639101948',
    projectId: 'fir-flutter-codelab-39c7d',
    storageBucket: 'fir-flutter-codelab-39c7d.appspot.com',
    iosClientId:
        '78639101948-uss9ssv9a9nq49pugfhrnrs737k4q9i2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFtc96wY31YzUZgykJQZcDnt7T-SEpu8Q',
    appId: '1:78639101948:ios:e8fd862041340204606479',
    messagingSenderId: '78639101948',
    projectId: 'fir-flutter-codelab-39c7d',
    storageBucket: 'fir-flutter-codelab-39c7d.appspot.com',
    iosClientId:
        '78639101948-4p2edrkb8m7sb14uv6bg5bhlvrdjj8r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
